version: '2.0'
services:
  dockerapp:
    extends:
      file: common.yml
      service: dockerapp 
    image: syraxius/dockerapp
    depends_on:
      - redis
    networks:
      - mynet

  redis:
    extends:
      file: common.yml
      service: redis
    networks:
      - mynet

networks:
  mynet:
    driver: overlay
